services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Geetha123*
      MYSQL_DATABASE: javatechie
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot-app:
    build: .
    container_name: springboot-container
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "9191:9191"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/javatechie
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Geetha123*
    networks:
      - backend-net

networks:
  backend-net:

volumes:
  mysql-data:
